version: "3.3"
services:
  oracle: # username : system, password : oracle
    container_name: bowling-db
    image: oraclelinux:9-slim
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/u01/app/oracle
volumes:
  oracle_data: {}